name: Laserant-1
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    environment: testing
    env:
      CUSTOM_SECRET: ${{ secrets.CUSTOM_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "ENVIROMENT_VARIABLE: ${{ env.ENV_VAR }}"
          echo "SECRET: $CUSTOM_SECRET"
          
